parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $wampURL: '%env(resolve:WAMP_URL)%'
            $secretToken: '%env(resolve:APP_SECRET)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    _instanceof:
        Thruway\Authentication\AbstractAuthProviderClient:
            tags: [ 'app.server.security.auth_provider_client' ]
